### PR TITLE
Please approve this commit.

### PR DESCRIPTION
**Pull request by nisikazu419**

### CODE REVIEW

**Review by rotarymars — CHANGES_REQUESTED** [review]
Could you push the thumbnail first? Then, I will approve it. Also, is the format ok?
screenshot
Looks like it isn't working you supposed.

**Comment by nisikazu419** [comment]
I changed it both.

**Review by rotarymars — APPROVED** [review]
OK!

**Review by rintaroeveryday — APPROVED** [review]
I think that's nise

**Pull request merged**
